// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyToUploads(arg1) {
  return window['go']['main']['App']['CopyToUploads'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateStoryboard(arg1) {
  return window['go']['main']['App']['CreateStoryboard'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteStoryboard(arg1) {
  return window['go']['main']['App']['DeleteStoryboard'](arg1);
}

export function DeleteTake(arg1) {
  return window['go']['main']['App']['DeleteTake'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function GenerateTakeVideo(arg1) {
  return window['go']['main']['App']['GenerateTakeVideo'](arg1);
}

export function GetModelVersions() {
  return window['go']['main']['App']['GetModelVersions']();
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjects() {
  return window['go']['main']['App']['GetProjects']();
}

export function GetSavedAPIKey() {
  return window['go']['main']['App']['GetSavedAPIKey']();
}

export function GetTake(arg1) {
  return window['go']['main']['App']['GetTake'](arg1);
}

export function GetTakeStatus(arg1) {
  return window['go']['main']['App']['GetTakeStatus'](arg1);
}

export function HasAPIKey() {
  return window['go']['main']['App']['HasAPIKey']();
}

export function ListTakes(arg1) {
  return window['go']['main']['App']['ListTakes'](arg1);
}

export function SelectImageFile() {
  return window['go']['main']['App']['SelectImageFile']();
}

export function ToggleGoodTake(arg1) {
  return window['go']['main']['App']['ToggleGoodTake'](arg1);
}

export function UpdateAPIKey(arg1) {
  return window['go']['main']['App']['UpdateAPIKey'](arg1);
}

export function UpdateStoryboard(arg1) {
  return window['go']['main']['App']['UpdateStoryboard'](arg1);
}
