// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyToUploads(arg1:string):Promise<string>;

export function CreateProject(arg1:main.CreateProjectParams):Promise<void>;

export function CreateStoryboard(arg1:main.CreateStoryboardParams):Promise<void>;

export function DeleteProject(arg1:number):Promise<void>;

export function DeleteStoryboard(arg1:number):Promise<number>;

export function DeleteTake(arg1:number):Promise<main.DeleteTakeResult>;

export function ExportProject(arg1:number):Promise<void>;

export function GenerateTakeVideo(arg1:number):Promise<Record<string, any>>;

export function GetModelVersions():Promise<Array<Record<string, string>>>;

export function GetProject(arg1:number):Promise<main.ProjectDetailData>;

export function GetProjects():Promise<main.ProjectsData>;

export function GetSavedAPIKey():Promise<string>;

export function GetTake(arg1:number):Promise<main.TakeResponse>;

export function GetTakeStatus(arg1:number):Promise<main.TakeStatusResult>;

export function HasAPIKey():Promise<boolean>;

export function ListTakes(arg1:number):Promise<Array<main.TakeResponse>>;

export function SelectImageFile():Promise<string>;

export function ToggleGoodTake(arg1:number):Promise<boolean>;

export function UpdateAPIKey(arg1:string):Promise<void>;

export function UpdateStoryboard(arg1:main.UpdateStoryboardParams):Promise<void>;
